# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EbO3U1xMhvI5oM5SdH6epmJ8D9UfEuU
"""



"""## Streamlit App

Below is the code for a basic Streamlit application that integrates the data collection, feature engineering, model training, visualization, and prediction functions from this notebook. You would typically save this code to a Python file (e.g., `streamlit_app.py`) and run it from your terminal using `streamlit run streamlit_app.py`.
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# --- Function Definitions (copied for self-contained app) ---

def get_stock_data(ticker_symbol):
    df = yf.download(ticker_symbol, start="2019-01-01", end="2024-01-01")

    df['MA_5']         = df['Close'].rolling(5).mean()
    df['MA_20']        = df['Close'].rolling(20).mean()
    df['Momentum']     = df['Close'].pct_change(5)
    df['Volatility']   = df['Close'].rolling(10).std()
    df['Volume_Change']= df['Volume'].pct_change()

    df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)

    df.dropna(inplace=True)
    return df

def train_model(df):
    features = ['MA_5', 'MA_20', 'Momentum', 'Volatility', 'Volume_Change']
    X = df[features]
    y = df['Target']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    preds = model.predict(X_test)
    accuracy = accuracy_score(y_test, preds)

    return model, accuracy, X_test, y_test

def plot_stock(df, ticker_symbol):
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df.index, y=df['Close'].squeeze(),
        name='Close Price',
        line=dict(color='#2196F3', width=2)
    ))

    fig.add_trace(go.Scatter(
        x=df.index, y=df['MA_5'].squeeze(),
        name='5-Day MA',
        line=dict(color='#FF9800', width=1.5, dash='dot')
    ))

    fig.add_trace(go.Scatter(
        x=df.index, y=df['MA_20'].squeeze(),
        name='20-Day MA',
        line=dict(color='#4CAF50', width=1.5, dash='dash')
    ))

    fig.update_layout(
        title=f'{ticker_symbol} — Price & Moving Averages',
        xaxis_title='Date',
        yaxis_title='Price (USD)',
        template='plotly_dark',
        hovermode='x unified',
        legend=dict(orientation='h', yanchor='bottom', y=1.02)
    )

    return fig

def predict(model, df):
    features = ['MA_5', 'MA_20', 'Momentum', 'Volatility', 'Volume_Change']

    latest = df[features].iloc[-1].values.reshape(1, -1)
    prediction = model.predict(latest)[0]
    probability = model.predict_proba(latest)[0]

    direction = "📈 UP" if prediction == 1 else "📉 DOWN"
    confidence = round(max(probability) * 100, 2)

    return direction, confidence

def generate_signal(prediction_numeric, confidence):
    if prediction_numeric == 1 and confidence > 60: # Using 60% as threshold
        return "BUY"
    elif prediction_numeric == 0 and confidence > 60:
        return "SELL"
    else:
        return "HOLD"

# --- Streamlit App Layout ---

st.set_page_config(layout="wide")
st.title('Stock Price Direction Predictor')
st.write("Enter a stock ticker to get a prediction for the next day's price movement and a trading signal.")

ticker_input = st.text_input('Enter a stock ticker (e.g. AAPL, TSLA, NVDA):', 'AAPL').upper()

if st.button('Get Prediction'):
    if ticker_input:
        try:
            st.subheader(f"Analyzing {ticker_input}...")

            # Data Collection & Feature Engineering
            df = get_stock_data(ticker_input)

            if df.empty:
                st.warning(f"Could not retrieve data for {ticker_input}. Please check the ticker symbol.")
            else:
                # Model Training
                model, accuracy, _, _ = train_model(df)
                st.write(f"Model Accuracy for {ticker_input}: **{round(accuracy * 100, 2)}%**")

                # Visualization
                st.subheader("Price & Moving Averages")
                fig = plot_stock(df, ticker_input)
                st.plotly_chart(fig, use_container_width=True)

                # Prediction
                direction, confidence = predict(model, df)
                prediction_numeric = 1 if "UP" in direction else 0
                signal = generate_signal(prediction_numeric, confidence)

                st.subheader("Prediction for Tomorrow")
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Direction", direction)
                with col2:
                    st.metric("Confidence", f"{confidence}%")
                with col3:
                    st.metric("Signal", signal)

        except Exception as e:
            st.error(f"An error occurred: {e}")
    else:
        st.warning("Please enter a ticker symbol.")
